apiVersion: apps/v1
kind: Deployment
metadata:
  name: algo-next
  labels:
    app: algo-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algo-next
  template:
    metadata:
      labels:
        app: algo-next
    spec:
      containers:
        - name: algo-next
          image: 100xdevs/algo-next:dd58bbdf8980c18482e71dfc6bad04bd40c91793
          ports:
            - containerPort: 3000
            - containerPort: 5555
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: algo-arena-db
                  key: DATABASE_URL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: algo-arena-config
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: algo-arena-db
                  key: NEXTAUTH_SECRET
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: algo-arena-db
                  key: REDIS_URL
            - name: JUDGE0_URI
              valueFrom:
                secretKeyRef:
                  name: algo-arena-db
                  key: JUDGE0_URI
            - name: MOUNT_PATH
              valueFrom:
                configMapKeyRef:
                  name: algo-arena-config
                  key: MOUNT_PATH
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m 
              memory: 512Mi
          volumeMounts:
            - name: problems-pv
              mountPath: /problems
      volumes:
        - name: problems-pv
          persistentVolumeClaim:
            claimName: problems-claim